CREATE TABLE `drug_classes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`nameEn` varchar(100),
	`description` text,
	`cardiotoxicityType` enum('tipo_I','tipo_II','misto','nenhum') DEFAULT 'nenhum',
	`cardiotoxicityMechanism` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `drug_classes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `drug_interactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`drug1Id` int NOT NULL,
	`drug2Name` varchar(150) NOT NULL,
	`severity` enum('contraindicada','grave','moderada','leve') NOT NULL,
	`mechanism` text,
	`clinicalEffect` text,
	`management` text,
	`qtRisk` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `drug_interactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `medications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`genericName` varchar(150) NOT NULL,
	`brandNames` text,
	`drugClassId` int NOT NULL,
	`mechanismOfAction` text,
	`indications` text,
	`standardDose` text,
	`doseUnit` varchar(50),
	`maxCumulativeDose` float,
	`maxCumulativeDoseUnit` varchar(30),
	`cardiotoxicityRisk` enum('baixo','moderado','alto','muito_alto') DEFAULT 'baixo',
	`cardiotoxicityProfile` text,
	`lvefMonitoring` boolean DEFAULT false,
	`qtProlongation` boolean DEFAULT false,
	`hypertensionRisk` boolean DEFAULT false,
	`myocarditisRisk` boolean DEFAULT false,
	`renalAdjustment` text,
	`hepaticAdjustment` text,
	`mainSideEffects` text,
	`cardioProtection` text,
	`references` text,
	`sbocGuideline` varchar(200),
	`escGuideline` varchar(200),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `medications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `monitoring_schedules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`medicationId` int NOT NULL,
	`timepoint` varchar(100) NOT NULL,
	`echocardiogram` boolean DEFAULT false,
	`ecg` boolean DEFAULT false,
	`troponin` boolean DEFAULT false,
	`bnp` boolean DEFAULT false,
	`bloodPressure` boolean DEFAULT false,
	`cbc` boolean DEFAULT false,
	`renalFunction` boolean DEFAULT false,
	`hepaticFunction` boolean DEFAULT false,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `monitoring_schedules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `patient_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`userId` int NOT NULL,
	`assessmentDate` timestamp NOT NULL DEFAULT (now()),
	`currentMedicationId` int,
	`currentMedicationName` varchar(150),
	`cumulativeDose` float,
	`cumulativeDoseUnit` varchar(30),
	`treatmentCycle` int,
	`lvef` float,
	`lvefMethod` varchar(50),
	`troponin` float,
	`troponinType` varchar(20),
	`bnp` float,
	`qtcInterval` float,
	`systolicBp` int,
	`diastolicBp` int,
	`heartRate` int,
	`dyspnea` boolean DEFAULT false,
	`chestPain` boolean DEFAULT false,
	`palpitations` boolean DEFAULT false,
	`edema` boolean DEFAULT false,
	`ctcaeGrade` int,
	`ctcaeToxicity` varchar(100),
	`recommendation` text,
	`treatmentModification` enum('manter','reduzir_dose','suspender_temporario','descontinuar','aguardar'),
	`nextAssessmentDate` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `patient_assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `patients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`birthDate` timestamp,
	`sex` enum('masculino','feminino','outro'),
	`weightKg` float,
	`heightCm` float,
	`creatinine` float,
	`hypertension` boolean DEFAULT false,
	`diabetes` boolean DEFAULT false,
	`dyslipidemia` boolean DEFAULT false,
	`smoking` boolean DEFAULT false,
	`obesity` boolean DEFAULT false,
	`previousHeartDisease` boolean DEFAULT false,
	`previousChemotherapy` boolean DEFAULT false,
	`oncologicDiagnosis` varchar(200),
	`tumorStage` varchar(50),
	`baselineLvef` float,
	`baselineTroponin` float,
	`baselineBnp` float,
	`cardiovascularRisk` enum('baixo','moderado','alto','muito_alto'),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `patients_id` PRIMARY KEY(`id`)
);
